//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import Moya

enum ___VARIABLE_sceneName___Request {
    
    struct FetchItems: ParamTargetType {
        
        struct Request: Codable {
            
        }
        
        struct Response: StandardResponseProtocol {
            let code: String
            let message: String
            
            enum CodingKeys: String, CodingKey {
                case code = "Code"
                case message = "Message"
            }
        }
        
        typealias RequestType = Request
        typealias ResponseType = Response
        
        var param: RequestType
        
        init(param: RequestType) {
            self.param = param
        }
        
        var path: String {
            ""
        }
        
    }
    
}
