//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import Moya

enum ___VARIABLE_sceneName___Request {
    
    struct FetchItems: ParamTargetType {
        
        typealias RequestType = ___VARIABLE_sceneName___Models.SomeThing.Request
        typealias ResponseType = ___VARIABLE_sceneName___Models.SomeThing.Response
        
        var param: RequestType
        
        init(param: RequestType) {
            self.param = param
        }
        
        var path: String {
            ""
        }
        
    }
    
}
